version: '3.8'

services:
  react-app:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
      - /app/node_modules
#      - /var/www/kamilholub.pl/html:/var/www/kamilholub.pl/html
